import {
  WeaponDef,
  PassiveDef,
  SynergyDef,
  EnemyDef,
  MetaUpgradeDef,
  StageDef,
  AchievementDef
} from '../types/game';

export const WEAPONS: Record<string, WeaponDef> = {
  wolven_headbutt: {
    id: 'wolven_headbutt',
    name: 'Wolven Headbutt',
    category: 'physical',
    description: 'Build up speed while running to sprout a battering arc that blocks damage and pushes back foes.',
    icon: '🐂',
    baseDamage: 20,
    cooldownMs: 0,
    range: 25,
    projectiles: 1,
    speed: 0,
    color: '#d97706',
    maxLevel: 5,
    formExclusive: 'werewolf',
  },
  werewolf_claws: {
    id: 'werewolf_claws',
    name: 'Werewolf Claws',
    category: 'physical',
    description: 'Ferocious melee slashes in front of you. Power increases during Full Moon.',
    icon: '🐾',
    baseDamage: 34,
    cooldownMs: 800,
    range: 72,
    projectiles: 1,
    speed: 0,
    color: '#ef4444',
    maxLevel: 8,
    formExclusive: 'werewolf',
  },
  tail_sweep: {
    id: 'tail_sweep',
    name: 'Tail Sweep',
    category: 'physical',
    description: 'A sweeping tail strike that knocks back enemies behind you.',
    icon: '🐉',
    baseDamage: 30,
    cooldownMs: 2000,
    range: 100,
    projectiles: 1,
    speed: 0,
    color: '#dc2626',
    maxLevel: 8,
    formExclusive: 'werewolf',
  },
  slashing_dash: {
    id: 'slashing_dash',
    name: 'Slashing Dash',
    category: 'physical',
    description: 'Leaps forward into a spinning blade strike while invulnerable.',
    icon: '🗡️',
    baseDamage: 45,
    cooldownMs: 4000,
    range: 300,
    projectiles: 1,
    speed: 0,
    color: '#f97316',
    maxLevel: 8,
    formExclusive: 'werewolf',
  },
  lightning_teeth: {
    id: 'lightning_teeth',
    name: 'Lightning Teeth',
    category: 'magical',
    description: 'Delivers an electrified bite that shocks nearby foes.',
    icon: '⚡',
    baseDamage: 12,
    cooldownMs: 500,
    range: 50,
    projectiles: 1,
    speed: 0,
    color: '#facc15',
    maxLevel: 8,
    formExclusive: 'werewolf',
  },
  silver_crossbow: {
    id: 'silver_crossbow',
    name: 'Silver Crossbow',
    category: 'physical',
    description: 'Fires high-speed piercing silver bolts at nearby foes.',
    icon: '🏹',
    baseDamage: 22,
    cooldownMs: 1100,
    range: 300,
    projectiles: 1,
    speed: 12,
    color: '#e2e8f0',
    maxLevel: 8,
  },
  frost_orb: {
    id: 'frost_orb',
    name: 'Frost Orb',
    category: 'magical',
    description: 'Launches icy spheres that freeze and slow surrounding enemies.',
    icon: '❄️',
    baseDamage: 18,
    cooldownMs: 1400,
    range: 200,
    projectiles: 1,
    speed: 7,
    color: '#38bdf8',
    maxLevel: 8,
  },
  earth_shatter: {
    id: 'earth_shatter',
    name: 'Earth Shatter',
    category: 'physical',
    description: 'Slams the ground with a heavy shockwave, shattering frozen foes.',
    icon: '🔨',
    baseDamage: 40,
    cooldownMs: 2200,
    range: 90,
    projectiles: 1,
    speed: 0,
    color: '#d97706',
    maxLevel: 8,
  },
  lunar_beam: {
    id: 'lunar_beam',
    name: 'Lunar Ray',
    category: 'magical',
    description: 'Calls down radiant moonbeams to scorch columns of enemies.',
    icon: '🌙',
    baseDamage: 35,
    cooldownMs: 2500,
    range: 175,
    projectiles: 1,
    speed: 0,
    color: '#a855f7',
    maxLevel: 8,
  },
  silver_daggers: {
    id: 'silver_daggers',
    name: 'Silver Daggers',
    category: 'physical',
    description: 'Throws silver daggers in rapid multi-directional fans.',
    icon: '🗡️',
    baseDamage: 15,
    cooldownMs: 700,
    range: 300,
    projectiles: 2,
    speed: 10,
    color: '#94a3b8',
    maxLevel: 8,
  },
  blood_ring: {
    id: 'blood_ring',
    name: 'Blood Ring',
    category: 'physical',
    description: 'A crimson aura that drains health from surrounding foes.',
    icon: '🩸',
    baseDamage: 12,
    cooldownMs: 1200,
    range: 70,
    projectiles: 1,
    speed: 0,
    color: '#dc2626',
    maxLevel: 8,
  },
  wolf_pack: {
    id: 'wolf_pack',
    name: 'Spectral Wolf Pack',
    category: 'physical',
    description: 'Summons spectral silver wolves that roam and charge at foes.',
    icon: '🐺',
    baseDamage: 25,
    cooldownMs: 3000,
    range: 350,
    projectiles: 1,
    speed: 8,
    color: '#6366f1',
    maxLevel: 8,
  },
  burning_steps: {
    id: 'burning_steps',
    name: 'Burning Steps',
    category: 'magical',
    description: 'Leaves a scorching trail of fire underfoot that ignites trailing enemies.',
    icon: '🔥',
    baseDamage: 3,
    cooldownMs: 1000,
    range: 45,
    projectiles: 1,
    speed: 0,
    color: '#f97316',
    maxLevel: 8,
  },
  silver_decapitator: {
    id: 'silver_decapitator',
    name: 'Silver Decapitator',
    category: 'physical',
    description: 'Unleashes a wide silver blade arc across your front.',
    icon: '⚔️',
    baseDamage: 38,
    cooldownMs: 1200,
    range: 90,
    projectiles: 1,
    speed: 0,
    color: '#e2e8f0',
    maxLevel: 5,
    formExclusive: 'human',
  },
  decoy: {
    id: 'decoy',
    name: 'Decoy',
    category: 'magical',
    description: 'Deploys a sturdy dummy that taunts and draws enemy attacks away from you.',
    icon: '🪆',
    baseDamage: 0,
    cooldownMs: 15000,
    range: 50,
    projectiles: 1,
    speed: 0,
    color: '#34d399',
    maxLevel: 5,
    formExclusive: 'human',
  },
  lightning_rod: {
    id: 'lightning_rod',
    name: 'Lightning Rod',
    category: 'magical',
    description: 'Calls down chain lightning that arcs between nearby enemies.',
    icon: '⚡',
    baseDamage: 30,
    cooldownMs: 1600,
    range: 150,
    projectiles: 1,
    speed: 0,
    color: '#fef08a',
    maxLevel: 5,
    formExclusive: 'human',
  },
  searing_gloves: {
    id: 'searing_gloves',
    name: 'Searing Gloves',
    category: 'magical',
    description: 'Unleashes twin bursts of flame that ignite surrounding foes.',
    icon: '🥊',
    baseDamage: 28,
    cooldownMs: 1400,
    range: 200,
    projectiles: 2,
    speed: 0,
    color: '#f97316',
    maxLevel: 5,
    formExclusive: 'human',
  },
};

export const PASSIVES: Record<string, PassiveDef> = {
  blood_stone: {
    id: 'blood_stone',
    name: 'Blood Stone',
    description: 'Increases Health Regeneration and Lifesteal rate.',
    icon: '💎',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'HP Regen', value: 0.8, unit: 'HP/s' },
  },
  moon_pendant: {
    id: 'moon_pendant',
    name: 'Moon Pendant',
    description: 'Increases XP Gain and Gem Pickup Magnet range.',
    icon: '📿',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'XP & Magnet', value: 20, unit: '%' },
  },
  silver_armor: {
    id: 'silver_armor',
    name: 'Silver Armor',
    description: 'Increases Max Health and Armor damage reduction.',
    icon: '🛡️',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Max HP & Armor', value: 25, unit: 'HP' },
  },
  quickstep_boots: {
    id: 'quickstep_boots',
    name: 'Quickstep Boots',
    description: 'Increases Movement Speed.',
    icon: '👢',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Move Speed', value: 10, unit: '%' },
  },
  chrono_hourglass: {
    id: 'chrono_hourglass',
    name: 'Chrono Hourglass',
    description: 'Reduces all weapon attack cooldown times.',
    icon: '⏳',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Cooldown Reduction', value: 8, unit: '%' },
  },
  wolf_fang: {
    id: 'wolf_fang',
    name: 'Wolf Fang',
    description: 'Increases Critical Hit Chance and Critical Damage.',
    icon: '🦷',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Crit Chance', value: 7, unit: '%' },
  },
  philosopher_ring: {
    id: 'philosopher_ring',
    name: 'Philosopher Ring',
    description: 'Increases Gold drops and Lunar Shard generation.',
    icon: '💍',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Gold Drop Rate', value: 25, unit: '%' },
  },
  sunglasses: {
    id: 'sunglasses',
    name: 'Sunglasses',
    description: 'Extends Night form while shortening Day form.',
    icon: '🕶️',
    maxLevel: 3,
    statBoostPerLevel: { stat: 'Night +5s / Day -5s', value: 5, unit: 's' },
    formExclusive: 'werewolf',
  },
  bloodlust_amulet: {
    id: 'bloodlust_amulet',
    name: 'Bloodlust Amulet',
    description: 'Gains a stacking damage bonus for each recently slain enemy.',
    icon: '📿',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Damage per Kill', value: 5, unit: '%' },
    formExclusive: 'werewolf',
  },
  alarm_clock: {
    id: 'alarm_clock',
    name: 'Alarm Clock',
    description: 'Extends Day form while shortening Night form.',
    icon: '⏰',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Day +20% / Night -20%', value: 20, unit: '%' },
    formExclusive: 'human',
  },
  meditation_mat: {
    id: 'meditation_mat',
    name: 'Meditation Mat',
    description: 'Regenerates health while standing still away from enemies.',
    icon: '🧘',
    maxLevel: 5,
    statBoostPerLevel: { stat: 'Stationary Heal', value: 5, unit: '%/s' },
    formExclusive: 'human',
  },
};

export const SYNERGIES: SynergyDef[] = [
  {
    id: 'frost_shatter',
    name: 'Frost Shatter Combo',
    description: 'Frost Orb freezes enemies -> Earth Shatter shatters them into deadly ice shards causing 3x CRIT explosions!',
    requiredWeapons: ['frost_orb', 'earth_shatter'],
    icon: '🧊💥',
    color: '#38bdf8',
    effectType: 'shatter',
  },
  {
    id: 'blood_ignite',
    name: 'Vampiric Inferno',
    description: 'Burning Steps ignites foes -> Blood Ring leeching ignited foes grants DOUBLE lifesteal!',
    requiredWeapons: ['burning_steps', 'blood_ring'],
    icon: '🔥🩸',
    color: '#ef4444',
    effectType: 'vampirism',
  },
  {
    id: 'silver_storm',
    name: 'Silver Tempest',
    description: 'Silver Crossbow bolts explode into multi-directional Silver Daggers on impact!',
    requiredWeapons: ['silver_crossbow', 'silver_daggers'],
    icon: '🏹🗡️',
    color: '#cbd5e1',
    effectType: 'dagger_storm',
  },
  {
    id: 'lunar_claw',
    name: 'Moonlight Berserk',
    description: 'Werewolf Claws unleash wave arcs of Lunar Beam light during Night form!',
    requiredWeapons: ['werewolf_claws', 'lunar_beam'],
    icon: '🐾🌙',
    color: '#c084fc',
    effectType: 'lunar_claw',
  },
];

export const ENEMIES: Record<string, EnemyDef> = {
  peasant: {
    type: 'peasant',
    name: 'Pitchfork Peasant',
    hp: 14,
    speed: 1.35,
    damage: 8,
    xpValue: 12,
    goldChance: 0.15,
    color: '#a16207',
    radius: 12,
  },
  torch_hunter: {
    type: 'torch_hunter',
    name: 'Torch Hunter',
    hp: 24,
    speed: 1.575,
    damage: 12,
    xpValue: 20,
    goldChance: 0.25,
    color: '#ea580c',
    radius: 14,
    isRanged: true,
  },
  silver_knight: {
    type: 'silver_knight',
    name: 'Silver Order Knight',
    hp: 60,
    speed: 1.05,
    damage: 18,
    xpValue: 45,
    goldChance: 0.4,
    color: '#94a3b8',
    radius: 18,
  },
  dire_hound: {
    type: 'dire_hound',
    name: 'Inquisition Hound',
    hp: 18,
    speed: 2.4,
    damage: 14,
    xpValue: 25,
    goldChance: 0.2,
    color: '#475569',
    radius: 11,
  },
  holy_cleric: {
    type: 'holy_cleric',
    name: 'Sun Cleric',
    hp: 40,
    speed: 1.2,
    damage: 10,
    xpValue: 35,
    goldChance: 0.35,
    color: '#facc15',
    radius: 15,
  },
  vampire_thrall: {
    type: 'vampire_thrall',
    name: 'Rogue Thrall',
    hp: 34,
    speed: 1.875,
    damage: 16,
    xpValue: 30,
    goldChance: 0.3,
    color: '#881337',
    radius: 13,
  },
  shield_vanguard: {
    type: 'shield_vanguard',
    name: 'Shield Vanguard',
    hp: 45,
    shield: 45,
    speed: 1.15,
    damage: 15,
    xpValue: 35,
    goldChance: 0.35,
    color: '#38bdf8',
    radius: 16,
  },
  volatile_zealot: {
    type: 'volatile_zealot',
    name: 'Volatile Zealot',
    hp: 22,
    speed: 1.65,
    damage: 10,
    xpValue: 28,
    goldChance: 0.3,
    color: '#ef4444',
    radius: 13,
    isExploding: true,
  },
  inquisition_trapper: {
    type: 'inquisition_trapper',
    name: 'Inquisition Trapper',
    hp: 35,
    speed: 1.1,
    damage: 8,
    xpValue: 32,
    goldChance: 0.3,
    color: '#ca8a04',
    radius: 14,
    isNetThrower: true,
  },
  spike_warden: {
    type: 'spike_warden',
    name: 'Spike Warden',
    hp: 55,
    speed: 1.0,
    damage: 16,
    xpValue: 40,
    goldChance: 0.35,
    color: '#71717a',
    radius: 17,
    isSpiky: true,
  },
  boss_inquisitor: {
    type: 'boss_inquisitor',
    name: 'High Inquisitor Malakor',
    hp: 1000,
    speed: 0.9,
    damage: 35,
    xpValue: 500,
    goldChance: 1.0,
    color: '#e11d48',
    radius: 32,
    isBoss: true,
  },
  boss_alpha_wolf: {
    type: 'boss_alpha_wolf',
    name: 'Corrupted Rival Alpha',
    hp: 1600,
    speed: 2.1,
    damage: 45,
    xpValue: 800,
    goldChance: 1.0,
    color: '#4c1d95',
    radius: 36,
    isBoss: true,
  },
};

export const META_UPGRADES: MetaUpgradeDef[] = [
  {
    id: 'health',
    name: 'Lycan Endurance',
    description: 'Permanently increases Max Health by +20 per level.',
    icon: '❤️',
    maxLevel: 10,
    costBase: 40,
    costMultiplier: 1.5,
    effectPerLevel: '+20 Max HP',
    currency: 'lunar_shards',
  },
  {
    id: 'damage',
    name: 'Ferocity Might',
    description: 'Permanently boosts overall weapon damage by +8% per level.',
    icon: '⚔️',
    maxLevel: 10,
    costBase: 50,
    costMultiplier: 1.6,
    effectPerLevel: '+8% Damage',
    currency: 'lunar_shards',
  },
  {
    id: 'speed',
    name: 'Lunar Agility',
    description: 'Permanently increases movement speed by +5% per level.',
    icon: '⚡',
    maxLevel: 5,
    costBase: 35,
    costMultiplier: 1.6,
    effectPerLevel: '+5% Speed',
    currency: 'lunar_shards',
  },
  {
    id: 'magnet',
    name: 'Gravitational Aura',
    description: 'Permanently boosts gem/gold pickup radius by +25% per level.',
    icon: '🧲',
    maxLevel: 5,
    costBase: 30,
    costMultiplier: 1.5,
    effectPerLevel: '+25% Pickup Range',
    currency: 'lunar_shards',
  },
  {
    id: 'greed',
    name: 'Bounty Hunter',
    description: 'Permanently increases Gold and Lunar Shards drop rates by +20% per level.',
    icon: '💰',
    maxLevel: 5,
    costBase: 45,
    costMultiplier: 1.6,
    effectPerLevel: '+20% Gold & Shards',
    currency: 'lunar_shards',
  },
  {
    id: 'wisdom',
    name: 'Blood Memory',
    description: 'Permanently increases XP gain rate by +15% per level.',
    icon: '🧠',
    maxLevel: 5,
    costBase: 40,
    costMultiplier: 1.6,
    effectPerLevel: '+15% XP Gain',
    currency: 'lunar_shards',
  },
  {
    id: 'cooldown',
    name: 'Quick Reflexes',
    description: 'Permanently reduces weapon attack cooldowns by -5% per level.',
    icon: '⏱️',
    maxLevel: 5,
    costBase: 50,
    costMultiplier: 1.7,
    effectPerLevel: '-5% Cooldown',
    currency: 'lunar_shards',
  },
  {
    id: 'rerolls',
    name: 'Oracle Insights',
    description: 'Grants +1 Reroll option in the Level Up upgrade menu per run.',
    icon: '🎲',
    maxLevel: 3,
    costBase: 60,
    costMultiplier: 1.8,
    effectPerLevel: '+1 Reroll/Run',
    currency: 'lunar_shards',
  },
  {
    id: 'revive',
    name: 'Moonlight Rebirth',
    description: 'Grants +1 Free Auto-Revive with 50% HP upon death per level.',
    icon: '✨',
    maxLevel: 2,
    costBase: 5,
    costMultiplier: 2.5,
    effectPerLevel: '+1 Extra Life',
    currency: 'ichor_crystals',
  },
];

export const STAGES: StageDef[] = [
  {
    id: 'forest',
    name: 'Whispering Woods',
    description: 'Dense dark forest overrun by angry townspeople and hound packs.',
    recommendedLevel: 'Beginner',
    bgTileColor: '#0f172a',
    borderColor: '#1e293b',
    spawnRates: {
      peasant: 0.35,
      torch_hunter: 0.2,
      dire_hound: 0.15,
      volatile_zealot: 0.1,
      inquisition_trapper: 0.1,
      spike_warden: 0.1,
    },
    bossAtSeconds: [180, 360, 600], // 3m, 6m, 10m
  },
  {
    id: 'citadel',
    name: 'Silver Citadel Outskirts',
    description: 'Fortified grounds filled with armored knights and holy clerics.',
    recommendedLevel: 'Challenging',
    bgTileColor: '#18181b',
    borderColor: '#27272a',
    spawnRates: {
      peasant: 0.15,
      silver_knight: 0.25,
      holy_cleric: 0.15,
      vampire_thrall: 0.15,
      shield_vanguard: 0.15,
      inquisition_trapper: 0.075,
      spike_warden: 0.075,
    },
    bossAtSeconds: [180, 360, 600],
  },
];

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_blood',
    title: 'First Transformation',
    description: 'Survive your first Werewolf Full Moon cycle.',
    rewardType: 'lunar_shards',
    rewardAmount: 30,
    icon: '🌕',
    check: (_, gameStats) => (gameStats ? gameStats.transformationsCount >= 1 : false),
  },
  {
    id: 'slayer_100',
    title: 'Horde Cleanser',
    description: 'Defeat 100 enemies in a single run.',
    rewardType: 'lunar_shards',
    rewardAmount: 50,
    icon: '⚔️',
    check: (_, gameStats) => (gameStats ? gameStats.kills >= 100 : false),
  },
  {
    id: 'survivor_5m',
    title: 'Night Stalker',
    description: 'Survive for at least 5 minutes (300 seconds).',
    rewardType: 'lunar_shards',
    rewardAmount: 80,
    icon: '⏱️',
    check: (_, gameStats) => (gameStats ? gameStats.timeSurvivedSeconds >= 300 : false),
  },
  {
    id: 'synergy_master',
    title: 'Elemental Alchemist',
    description: 'Unlock any Weapon Synergy during a run.',
    rewardType: 'ichor_crystals',
    rewardAmount: 5,
    icon: '✨',
    check: (_, gameStats) => (gameStats ? gameStats.synergiesUnlocked.length >= 1 : false),
  },
  {
    id: 'slayer_1000',
    title: 'Alpha Legend',
    description: 'Defeat 1,000 enemies total across all runs.',
    rewardType: 'ichor_crystals',
    rewardAmount: 15,
    icon: '🏆',
    check: (data) => data.totalKills >= 1000,
  },
];
